#!/usr/bin/env bash

function _credstash_profile {
  local shome="${_credstash_home:="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$shome/exec:$PATH"
  #export ANSIBLE_ROLES_PATH="$shome/roles${ANSIBLE_ROLES_PATH:+:${ANSIBLE_ROLES_PATH}}"
  #export ANSIBLE_LIBRARY="$shome/library${ANSIBLE_LIBRARY:+:${ANSIBLE_LIBRARY}}"

  CREDSTASH_VERSION="$(cat "$shome/.credstash-version.json" | jq -r '.[].version')"
}

_credstash_profile
