#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_credstash="0.0.1"
  jq -n --arg credstash "$ver_credstash" '{credstash: $credstash}'
}

version "$@"
