#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  cd "$shome"
  local ver_credstash="$(pipenv run pip list --format json 2>/dev/null | jq -r 'map(select(.name == "credstash"))[].version' || true)"
  jq -n --arg credstash "$ver_credstash" '{credstash: $credstash}'
}

version "$@"
